//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment_posts
    {
        public long user_id { get; set; }
        public long post_id { get; set; }
        public string comment { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
