//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public int status { get; set; }
        public long user_id { get; set; }
        public long post_id { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
