//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstagramEntities : DbContext
    {
        public InstagramEntities()
            : base("name=InstagramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<user_requests> user_requests { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<comment_posts> comment_posts { get; set; }
    }
}
